# CI Routine for the album framework.

# Prevent duplicate pipelines: only run branch pipelines and cross-project triggers.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always

#----------------------------
# templates
#----------------------------

# Windows base template
#
# Downloads conda executable in <current_working_directory>\downloads if executable not present.
# Installs conda in >current_working_directory>\miniconda if conda not already installed.
# Runs conda initialization and configuration.
#
# NOTE: Apparently there is no output for commands split over several lines...
.windows_base_template_micromamba:
  tags:
    - windows
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR\.cache\pip
    WINDOWS_MAMBA_ENV_PREFIX: .\AppData\Roaming\mamba\envs\album
    ErrorActionPreference: Continue # not working properly
  before_script:
    - 'echo "We are in path: $pwd "'
    - '$7ZIP_EXE=(Join-Path $env:ProgramFiles -ChildPath 7-Zip\7z.exe)'
    - "$7ZIP_INSTALLER=(Join-Path downloads -ChildPath 7z.exe)"
    - "$Env:USERPROFILE=$pwd" # set user profile to current working directory -> will be micromamba default location
    - '$oldProgressPreference = $progressPreference; $progressPreference = "SilentlyContinue";'
    - "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12" # set Security download protocol to avoid https errors
    - "if(-Not (Test-Path $7ZIP_EXE)) {if(-Not (Test-Path $7ZIP_INSTALLER)){Invoke-Webrequest -URI https://www.7-zip.org/a/7z2201-x64.exe -OutFile $7ZIP_INSTALLER}}"
    - 'if(-Not (Test-Path $7ZIP_EXE)) {Start-Process -FilePath $7ZIP_INSTALLER -Args "/S" -Verb RunAs -Wait}'
    - "Invoke-Webrequest -URI https://micro.mamba.pm/api/micromamba/win-64/$env:MICROMAMBA_CI_VERSION -OutFile micromamba.tar.bz2"
    - "& $7ZIP_EXE x micromamba.tar.bz2 -aoa"
    - '& $7ZIP_EXE x micromamba.tar -ttar -aoa -r Library\bin\micromamba.exe $("-o" + (Join-Path -Path (Get-Location) -ChildPath micromamba_installation))'
    - "$progressPreference = $oldProgressPreference"
    - 'Get-ChildItem Env: | Where-Object { $_.Name -match "album" -or $_.Value -match "album" } | Format-Table -AutoSize'
    - '.\micromamba_installation\Library\bin\micromamba.exe create -y -n album python=$env:TEST_PYTHON_VERSION -c conda-forge' # created under $env:WINDOWS_MAMBA_ENV_PREFIX
    - 'Write-Output "CI_COMMIT_REF_NAME: $env:CI_COMMIT_REF_NAME"'
    #- "$Env:MAMBA_ROOT_PREFIX=(Join-Path -Path (Get-Location) -ChildPath micromamba)"
    # The following lines allow to install the dev version of the API and envs in the album environment, based on the current branch name
    - 'if($env:CI_COMMIT_REF_NAME -match "api_change_runner*") { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX pip install git+https://gitlab.com/album-app/album-solution-api.git@dev}'
    - 'if($env:CI_COMMIT_REF_NAME -match "api_change_env*") { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX pip install git+https://gitlab.com/album-app/album-environments.git@dev}'
    # The following allows to install the dev version of the API and envs via CI variables on any branch
    - 'if($env:ALBUM_DEV_CORE_API -match "True") { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX pip install git+https://gitlab.com/album-app/album-solution-api.git@dev}'
    - 'if($env:ALBUM_DEV_CORE_ENV -match "True") { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX pip install git+https://gitlab.com/album-app/album-environments.git@dev}'
    - '.\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX pip install --no-cache-dir -e $Env:CI_PROJECT_DIR' # -e needed for coverage
    - '.\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX pip install coverage'
    - '$Env:ENVIRONMENT_DEBUGGING_MICROMAMBA_PATH=(Join-Path -Path (Get-Location) -ChildPath micromamba_installation\Library\bin\micromamba.exe)' # set environment variables necessary to work with the environment API
    - "$Env:ENVIRONMENT_CONDA_LOCK_PATH=(Get-Command conda-lock).Source" # explicitly set conda-lock path as it comes as dependency
  cache:
    key: one-key-to-rule-them-all-windows
    paths:
      - .cache\pip

# Linux base template for running tests with micromamba as package manager
#
# Uses a docker image where micromamba will be installed.
# Creates an album environment.
#

.linux_base_template_micromamba:
  image: ubuntu:latest
  tags:
    - docker
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    MICROMAMBA_EXECUTABLE: "" # ensure that the variable is empty before running the job
  before_script:
    - apt update || (sleep 30 && apt update) && apt install -y git curl bzip2
    - mkdir -p $CI_PROJECT_DIR/bin/
    - curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/$MICROMAMBA_CI_VERSION | tar -xvj -C $CI_PROJECT_DIR/bin/ --strip-components=1 bin/micromamba
    - MICROMAMBA_EXECUTABLE=$CI_PROJECT_DIR/bin/micromamba
    - $MICROMAMBA_EXECUTABLE create -y -n album -c conda-forge python=$TEST_PYTHON_VERSION
    - bash -c 'echo $CI_COMMIT_REF_NAME'
    # The following lines allow to install the dev version of the API and envs in the album environment, based on the current branch name
    - bash -c '[[ $CI_COMMIT_REF_NAME == api_change_runner* ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-solution-api.git@dev || echo "No api_change_runner branch"'
    - bash -c '[[ $CI_COMMIT_REF_NAME == api_change_env* ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-environments.git@dev || echo "No api_change_env branch"'
    # The following allows to install the dev version of the API and envs via CI variables on any branch
    - bash -c '[[ $ALBUM_DEV_CORE_ENV == "True" ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-environments.git@dev || echo "ALBUM_DEV_CORE_ENV not active"'
    - bash -c '[[ $ALBUM_DEV_CORE_API == "True" ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-solution-api.git@dev || echo "ALBUM_DEV_CORE_API not active"'
    - $MICROMAMBA_EXECUTABLE run -n album pip install --no-cache-dir -e $CI_PROJECT_DIR # -e needed for coverage
    - $MICROMAMBA_EXECUTABLE run -n album pip install coverage
    - $MICROMAMBA_EXECUTABLE run -n album python -V
    - $MICROMAMBA_EXECUTABLE run -n album pip list
    - $MICROMAMBA_EXECUTABLE run -n album env -0 | sort -z | tr '\0' '\n' | grep -i album
    - export ENVIRONMENT_DEBUGGING_MICROMAMBA_PATH=$MICROMAMBA_EXECUTABLE # set environment variables necessary to work with the environment API
    - export ENVIRONMENT_CONDA_LOCK_PATH=$(which conda-lock)
  cache:
    key: one-key-to-rule-them-all-linux
    paths:
      - .cache/pip

# Macos base template for running tests with micromamba as package manager
#
# Installs micromamba in a fresh tmp directory and activates it.
# DO NOT ALLOW JOBS TO BE RUN IN PARALLEL!
#
.macos_base_template_micromamba:
  tags:
    - macos
    - shell
  variables:
    MICROMAMBA_EXECUTABLE: "" # ensure that the variable is empty before running the job
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  before_script:
    - echo "$(uname)"
    - sw_vers
    - tmpdir=$(mktemp -d /tmp/album-test.XXXXXX)
    - echo $tmpdir
    - echo $tmpdir > /tmp/tmpdir
    - mkdir -p $tmpdir/bin/
    - curl -Ls https://micro.mamba.pm/api/micromamba/osx-64/$MICROMAMBA_CI_VERSION | tar -xvj -C $tmpdir/bin/ --strip-components=1 bin/micromamba
    - MICROMAMBA_EXECUTABLE=$tmpdir/bin/micromamba
    - $MICROMAMBA_EXECUTABLE create -y -n album -c conda-forge python=$TEST_PYTHON_VERSION
    - bash -c 'echo $CI_COMMIT_REF_NAME'
    # The following lines allow to install the dev version of the API and envs in the album environment, based on the current branch name
    - bash -c '[[ $CI_COMMIT_REF_NAME == api_change_runner* ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-solution-api.git@dev || echo "No api_change_runner branch"'
    - bash -c '[[ $CI_COMMIT_REF_NAME == api_change_env* ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-environments.git@dev || echo "No api_change_env branch"'
    # The following allows to install the dev version of the API and envs via CI variables on any branch
    - bash -c '[[ $ALBUM_DEV_CORE_ENV == "True" ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-environments.git@dev || echo "ALBUM_DEV_CORE_ENV not active"'
    - bash -c '[[ $ALBUM_DEV_CORE_API == "True" ]] && $MICROMAMBA_EXECUTABLE run -n album pip install git+https://gitlab.com/album-app/album-solution-api.git@dev || echo "ALBUM_DEV_CORE_API not active"'
    - $MICROMAMBA_EXECUTABLE run -n album pip install --no-cache-dir -e $CI_PROJECT_DIR # -e needed for coverage
    - $MICROMAMBA_EXECUTABLE run -n album pip install coverage
    - $MICROMAMBA_EXECUTABLE run -n album python -V
    - $MICROMAMBA_EXECUTABLE run -n album pip list
    - $MICROMAMBA_EXECUTABLE run -n album env -0 | sort -z | tr '\0' '\n' | grep -i album
    - export ENVIRONMENT_DEBUGGING_MICROMAMBA_PATH=$MICROMAMBA_EXECUTABLE # set environment variables necessary to work with the environment API
    - export ENVIRONMENT_CONDA_LOCK_PATH=$(which conda-lock)
  after_script:
    - tmpdir=$(</tmp/tmpdir)
    - echo $tmpdir
    - rm -rf $tmpdir

#----------------------------
# stages
#----------------------------

stages:
  - build
  - test
  - release-test
  - release
  - deploy
  - post-deploy

#----------------------------
# jobs
#----------------------------

rebuild_album_installer:
  stage: post-deploy
  trigger:
    project: album-app/plugins/album-package
  rules:
    - if: $ALBUM_DEV_CORE_API == "True" || $ALBUM_DEV_CORE_ENV == "True"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml

prepare release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - DeployRunner
    - DeployDocker
  script:
    - echo "preparing release"
    - VERSION=$(cat pyproject.toml | grep "version=*" | awk '{gsub(/"/, "", $3); print $3}')
    - TAG=v$VERSION
    - echo "prepare to release version $VERSION with tag $TAG"
    - echo "VERSION=$VERSION" >> variables.env
    - echo "TAG=v$VERSION" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env
  rules:
    - if: $ALBUM_DEV_CORE_API == "True" || $ALBUM_DEV_CORE_ENV == "True"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml

gitlab release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - DeployRunner
    - DeployDocker
  needs:
    - job: prepare release
      artifacts: true
  script:
    - echo "running release_job for version $VERSION and tag $TAG"
  rules:
    - if: $ALBUM_DEV_CORE_API == "True" || $ALBUM_DEV_CORE_ENV == "True"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml
  release:
    name: "Release $TAG"
    description: "Created using the release-cli"
    tag_name: "$TAG"
    ref: "$CI_COMMIT_SHA"

gitlab pypi deploy:
  image: python:$TEST_PYTHON_VERSION
  stage: deploy
  tags:
    - DeployRunner
    - DeployDocker
  needs:
    - job: gitlab release
    - job: prepare release
      artifacts: true
  script:
    - echo "deploying gitlab pypi version $VERSION"
    - pip install twine build
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $ALBUM_DEV_CORE_API == "True" || $ALBUM_DEV_CORE_ENV == "True"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml

pypi deploy:
  image: python:$TEST_PYTHON_VERSION
  stage: deploy
  tags:
    - DeployRunner
    - DeployDocker
  needs:
    - job: gitlab release
    - job: prepare release
      artifacts: true
  before_script:
    - echo "deploying pypi version $VERSION"
    - echo "using pypi deploy user $PYPI_DEPLOY_USER"
  script:
    - pip install twine build
    - python -m build
    - TWINE_PASSWORD=$PYPI_DEPLOY_TOKEN TWINE_USERNAME=$PYPI_DEPLOY_USER python -m twine upload --repository-url https://upload.pypi.org/legacy/  dist/*
  rules:
    - if: $ALBUM_DEV_CORE_API == "True" || $ALBUM_DEV_CORE_ENV == "True"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml

docker deploy:
  stage: deploy
  tags:
    - DeployRunner
    - DeployShell
  needs:
    - job: gitlab release
    - job: prepare release
      artifacts: true
    - job: pypi deploy
  before_script:
    - docker info
  script:
    - echo "deploying docker version $VERSION"
    - docker login -u "$DOCKER_DEPLOY_USER" -p "$DOCKER_DEPLOY_TOKEN" docker.io
    # building deploy tag
    - tag=$(echo $DOCKER_DEPLOY_USER/album:$VERSION)
    - echo "Building image with tag $tag"
    - docker build -t $tag .
    - docker push $tag
  rules:
    - if: $ALBUM_DEV_CORE_API == "True" || $ALBUM_DEV_CORE_ENV == "True"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml

# Linux Tests with coverage

cmdline linux:
  extends: .linux_base_template_micromamba
  stage: build
  script:
    - eval "$($MICROMAMBA_EXECUTABLE shell hook -s posix)"
    - micromamba activate album
    # album commands
    - album -h
    - album run -h
    - album install -h
    - album deploy -h
    - album uninstall -h
    - album repl -h
    - album add-catalog -h
    - album remove-catalog -h
    # album catalog admin
    - album-catalog-admin -h

unit tests linux micromamba:
  extends: .linux_base_template_micromamba
  stage: test
  script:
    - $MICROMAMBA_EXECUTABLE run -n album coverage run --omit './test/*' -m unittest test/unit/run_all_unit_micromamba.py
    - $MICROMAMBA_EXECUTABLE run -n album coverage report
    - mv .coverage unit.coverage # rename coverage file
  artifacts:
    paths:
      - unit.coverage

integration tests linux micromamba:
  extends: .linux_base_template_micromamba
  stage: test
  script:
    - $MICROMAMBA_EXECUTABLE run -n album coverage run --omit './test/*' -m unittest test/integration/run_all_integration_micromamba.py
    - $MICROMAMBA_EXECUTABLE run -n album coverage report
    - mv .coverage integration.coverage # rename coverage file
  artifacts:
    paths:
      - integration.coverage

# MacOs Tests

unit tests macos micromamba:
  extends: .macos_base_template_micromamba
  stage: test
  script:
    - $MICROMAMBA_EXECUTABLE run -n album python -m unittest test/unit/run_all_unit_micromamba.py

integration tests macos micromamba:
  extends: .macos_base_template_micromamba
  stage: test
  script:
    - $MICROMAMBA_EXECUTABLE run -n album python -m unittest test/integration/run_all_integration_micromamba.py

# Windows Tests with coverage

unit tests windows micromamba:
  extends: .windows_base_template_micromamba
  stage: test
  script:
    - '.\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage run --omit .\test\* -m unittest test\unit\run_all_unit_micromamba.py'
    - 'if ($lastexitcode -ne 0) {exit(1)} else { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage report }'
    - 'if ($lastexitcode -ne 0) {exit(1)} else { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage xml } '
    - 'if ($lastexitcode -ne 0) {exit(1)} else { Rename-Item -Path ".coverage" -NewName "unit.coverage" }'
    - 'if ($lastexitcode -ne 0) {exit(1)} else { Rename-Item -Path "coverage.xml" -NewName "unit_coverage.xml" }'
    - "exit($lastexitcode)"
  artifacts:
    paths:
      - unit.coverage

integration tests windows micromamba:
  extends: .windows_base_template_micromamba
  stage: test
  script:
    - '.\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage run --omit .\test\* -m unittest test\integration\run_all_integration_micromamba.py '
    - 'if ($lastexitcode -ne 0) {exit(1)} else { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage report }'
    - 'if ($lastexitcode -ne 0) {exit(1)} else { .\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage xml } '
    - 'if ($lastexitcode -ne 0) {exit(1)} else { Rename-Item -Path ".coverage" -NewName "integration.coverage" }'
    - 'if ($lastexitcode -ne 0) {exit(1)} else { Rename-Item -Path "coverage.xml" -NewName "integration_coverage.xml" }'
    - "exit($lastexitcode)"
  artifacts:
    paths:
      - integration.coverage

release tests linux:
  extends: .linux_base_template_micromamba
  stage: release-test
  script:
    # install system requirements
    - apt-get -y update
    - apt-get install -y libgl1-mesa-dev
    # install templates in default catalog
    # - album install album:template-python:0.1.0-SNAPSHOT
    # - album install album:template-java:0.1.0-SNAPSHOT
    # - album install album:template-r:0.1.0-SNAPSHOT
    # - album install album:template-scijava:0.1.0-SNAPSHOT
    # - album install album:template-imagej:0.1.0-SNAPSHOT
    # - album install album:template-imagej2:0.1.0-SNAPSHOT
    # - album install album:template-bdv:0.1.0-SNAPSHOT
    # - album install album:template-napari:0.1.0-SNAPSHOT
    # - album install album:template-minimal:0.1.0-SNAPSHOT
    # run non-interactive templates
    # - album run album:template-minimal:0.1.0-SNAPSHOT
    # - album run album:template-python:0.1.0-SNAPSHOT
    # - album run album:template-java:0.1.0-SNAPSHOT
    # - album run album:template-r:0.1.0-SNAPSHOT
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml

# Create combined coverage reports

create combined coverage for linux:
  extends: .linux_base_template_micromamba
  stage: test
  dependencies:
    - unit tests linux micromamba
    - integration tests linux micromamba
  needs:
    - unit tests linux micromamba
    - integration tests linux micromamba
  script:
    - $MICROMAMBA_EXECUTABLE run -n album coverage combine unit.coverage integration.coverage
    - $MICROMAMBA_EXECUTABLE run -n album coverage report
    - $MICROMAMBA_EXECUTABLE run -n album coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

create combined coverage for windows:
  extends: .windows_base_template_micromamba
  stage: test
  dependencies:
    - unit tests windows micromamba
    - integration tests windows micromamba
  needs:
    - unit tests windows micromamba
    - integration tests windows micromamba
  script:
    - '.\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage combine unit.coverage integration.coverage'
    - '.\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage report'
    - '.\micromamba_installation\Library\bin\micromamba.exe run -p $env:WINDOWS_MAMBA_ENV_PREFIX coverage xml'
    - "exit($lastexitcode)"
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
