name: hips
dependencies:
  - python>3.7,<3.8
  - pip
  - pyqt
  - natsort
  - google-cloud-storage
  - numba>=0.43.1
  - tqdm
  - numpy>1.14.6,<1.19.4
  - pip
  - scipy
  - pytorch>=1.6
  - opencv
  - pyqtgraph>=0.11.0rc0
  - natsort
  - google-cloud-storage
  - tqdm
  - tifffile
  - conda-forge::scyjava
  - conda-forge::pyimagej
